// <auto-generated/>
// <summary>
// GTD(getting things done) Application
// </summary>
// <copyright file="AggregatesByNotificationTypeDto.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace GtdApp.Data.Dto
{
    /// <summary>
    ///      AggregatesByNotificationTypeDto
    /// </summary>
    public class AggregatesByNotificationTypeDto
    {
        /// <summary>
        ///      Gets or sets Notification_type
        /// </summary>
        /// <value>string</value>
        public string Notification_type { get; set; }

        /// <summary>
        ///      Gets or sets Notification_count
        /// </summary>
        /// <value>int</value>
        public int Notification_count { get; set; }

        /// <summary>
        ///      Gets or sets item_count
        /// </summary>
        /// <value>int</value>
        public int Item_count { get; set; }
    }
}
